accessibilityJob: false
alwaysRunPostSteps: false
appium: null
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
captureScreenRecordingForScenarios: false
codeDirectory: lambdatest-se-assignment
collectLocalGitData: true
combineTasksInMatrixMode: false
concurrency: 1
cypress: false
differentialUpload:
    enabled: false
    forcedDisabled: false
    ttlHours: null
dynamicAllocation: false
env:
    TOKEN: anvdegtod-asdaasda0asda-asda
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        autoGrantPermissions: false
        avoidAppLaunch: false
        customData: {}
        darkMode: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        enableBluetooth: false
        enableResultBundle: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        localhost: false
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        networkLogsOptions:
            captureContent: false
            excludeHosts: []
            includeHosts: []
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        smartUI: null
        testRemarks: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands: []
    completed: false
    disableEmail: false
    downloadArtifacts: false
    email:
        linkValidity: 0
        metaInfo: []
        templatePath: ""
        to: []
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    commands: []
    completed: false
    location: ""
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    type: ""
    workingDirectory: ""
    yamlPath: null
jobID: 24e88476-a1f4-47f4-942d-b7334676416d
jobLabel:
    - selenium-testng
    - win
    - v1
    - autosplit
key: '********'
localHTTPProxy: ""
ltOptions: {}
maxRetries: 1
maxRetriesPreSteps: 0
meta: {}
onpremEnv: ""
platformConfig: null
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
pre:
    - mvn dependency:resolve
preDirectives:
    commands:
        - mvn dependency:resolve
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: 01KZXXTG2H47CF0RB6EGT03W60
    name: LambdaTest Default Project
    type: custom
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
retryOnFailure: true
runson: win11
runtime:
    language: java
    version: "11.0"
    addons: []
    opts: {}
slackChannel: ""
sourcePayload:
    verifySSL: true
sprofilePath: ""
storageType: ""
testDiscovery:
    autosubset: true
    command: grep 'test name' xml/testng_win.xml | awk '{print$2}' | sed 's/name=//g' | sed 's/\x3e//g'
    mode: dynamic
    type: raw
testDiscoveryResultV3: []
testRunnerCommand: mvn test -Dplatname=win -Dmaven.repo.local=./.m2 dependency:resolve -DselectedTests=$test
testSuites: []
triggerMode: false
triggerSource: CLI
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
user: sdattasai75
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
